# azure-pipelines.yml

trigger:
- master

jobs:
  - job: macos_build
    displayName: macos build
    pool:
      vmImage: 'macos-latest'
    steps:
    - task: CMake@1
      displayName: 'cmake configure'
      inputs:
        cmakeArgs: >
            -DCMAKE_INSTALL_PREFIX=${Build.ArtifactStagingDirectory}
            ${Build.SourcesDirectory}
    - task: CMake@1
      displayName: 'cmake install'
      inputs:
        cmakeArgs: >
             --build ./
             --target install
  - job: windows_build
    displayName: windows build
    pool:
      vmImage : windows-latest
    steps:
    - task: CMake@1
      displayName: 'cmake configure'
      inputs:
        cmakeArgs: >
            -DCMAKE_INSTALL_PREFIX=${Build.ArtifactStagingDirectory}
            ${Build.SourcesDirectory}
    - task: CMake@1
      displayName: 'cmake install'
      inputs:
        cmakeArgs: >
             --build ./
             --target install

